{% set name = "libhomfly" %}
{% set version = "1.03" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/miguelmarco/libhomfly/releases/download/{{ version }}/libhomfly-{{ version }}.tar.gz
  sha256: 2a06e93cccd91d33ed9c345eba2e59b2ba175c11e454cf2029644a9364250871

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("libhomfly", max_pin="x.x") }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make
  host:
    - bdw-gc

test:
  commands:
    - test -f $PREFIX/lib/libhomfly${SHLIB_EXT}
    - test -f $PREFIX/include/homfly.h

about:
  home: https://github.com/miguelmarco/libhomfly
  license: Unlicense
  license_family: MIT
  license_file: LICENSE
  summary: 'Library to compute the homfly polynomial of a link.'
  dev_url: https://github.com/miguelmarco/libhomfly

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
